---

- name: NEXUS | Include composer default vars
  include_vars: composer.yml

- name: NEXUS | Create composer proxy repository
  include_tasks: ../../script/run_script.yml
  with_items:
    - "{{ item.proxy | default([]) }}"
  loop_control:
    loop_var: proxy
  vars:
    script_name: composer_create_proxy_repository
    args: "{{ nexus_repositories_composer_default | combine(proxy) }}"

- name: NEXUS | Create composer hosted repository
  include_tasks: ../../script/run_script.yml
  with_items:
    - "{{ item.hosted | default([]) }}"
  loop_control:
    loop_var: hosted
  vars:
    script_name: composer_create_hosted_repository
    args: "{{ nexus_repositories_composer_default | combine(hosted) }}"

- name: NEXUS | Create composer group repository
  include_tasks: ../../script/run_script.yml
  with_items:
    - "{{ item.group | default([]) }}"
  loop_control:
    loop_var: group
  vars:
    script_name: composer_create_group_repository
    args: "{{ nexus_repositories_composer_default | combine(group) }}"
